/* This file is automatically generated. Do not edit it directly. */
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Fallbacks para garantir funcionamento mesmo sem .env */
const DEFAULT_SUPABASE_URL = 'https://blopdveolbwqajzklnzu.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb3BkdmVvbGJ3cWFqemtsbnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjg5NzIsImV4cCI6MjA3Nzk0NDk3Mn0.D_o4zB9fVanYoOiBO98-ED0G9v8JeUJrLb7JIDNtk5o';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = typeof envUrl === 'string' && envUrl.length > 0 ? envUrl : DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = typeof envKey === 'string' && envKey.length > 0 ? envKey : DEFAULT_SUPABASE_PUBLISHABLE_KEY;

if (!envUrl || !envKey) {
  console.warn('[Supabase] Variáveis de ambiente não encontradas. Usando valores padrão do projeto.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});